# Generated by Django 3.2 on 2021-05-27 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_contact_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='auth.user', verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Telefone'),
        ),
    ]
