# Generated by Django 3.2 on 2021-05-27 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210527_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'telephone')},
        ),
    ]
